name: 04-using-actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: printin folders  
              run: ls
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '22.x'
            - name: install dependencies 
              run: npm ci
            - name: Run Unit Tests
              run: npm run test    

# 0. Checkout the code from the repository
# 1. Install deps of our react application
# 2. Execute automated tests